import redis
import uuid

# -----------------------------------------
# Redis connection
# -----------------------------------------
redis_client = redis.Redis(
    host="localhost",
    port=6379,
    decode_responses=True
)

# -----------------------------------------
# Push query to queue
# -----------------------------------------
def enqueue_query(query: str):
    job_id = str(uuid.uuid4())

    payload = {
        "job_id": job_id,
        "query": query
    }

    redis_client.rpush("rag:requests", str(payload))
    return job_id


if __name__ == "__main__":
    user_query = input("> ")
    job_id = enqueue_query(user_query)

    print(f"Query submitted")
    print(f"Job ID: {job_id}")
